language: python

install:
  - pip install -r requirements-testing.txt -e . --use-mirrors

script: tox

after_success:
  - py.test --cov=google_ngram_downloader --cov-report=term-missing test
  - coveralls
